Notif suggestion (settings switch)
CoorpAcademy/mobile pull request #601
Opened 2020-09-07 21:09 UTC by alanlanglois

## Detailed purpose of the PR

Adding a new switch in settings for recommandation notifications.

### Testing strategy

- [ ] I ensured my code is tested: 
- [ ] I took care to mention breaking changes and extra libs if appropriate

2020-09-08 15:45 UTC, Fausto95 approved these changes

2020-09-08 15:45 UTC, Fausto95 commented on src/redux/reducers/notifications/suggestion.ts
> +  isActive: Platform.OS === 'android',
```suggestion
  isActive: true,
```

2020-09-08 15:45 UTC, Fausto95 commented on src/screens/settings.tsx
> +  notificationsSettings: Record<
```ts
notificationsSettings: {
    'finish-course': Pick<NotificationsState, 'finishCourse'>,
    suggestion: Pick<NotificationsState, 'suggestion'>
}
```

2020-09-08 15:45 UTC, Fausto95 commented on src/screens/settings.tsx
> +        }
I think we could have a single toggle function that takes in a type and does the actual toggle.

2020-09-08 15:45 UTC, Fausto95 requested changes
See comments

2020-09-08 15:47 UTC, Fausto95 commented on src/redux/reducers/notifications/suggestion.ts
> +  isActive: Platform.OS === 'android',
Don't take this comment is consideration,
But we should somewhere set this to true if the iOS user has already granted notifications permissions to us

2020-09-08 15:49 UTC, alanlanglois commented on src/screens/settings.tsx
> +        }
Yep, you're right it might be easier to maintain.

2020-09-09 14:25 UTC, Fausto95 commented on src/screens/settings.tsx
> +export const transformNotificationSettings = (settings: NotificationsSettingsState) => {
For some reason doing this transformation screws up the order of the elements, hence the sorting

2020-09-09 14:27 UTC, alanlanglois commented on src/redux/actions/notifications/scheduled-notifications.test.ts
> +          type: 'finish-course',
remove that

2020-09-09 15:21 UTC, merged