Refactor notifications settings status
CoorpAcademy/mobile pull request #609
Opened 2020-09-15 20:18 UTC by alanlanglois

## Detailed purpose of the PR

[iOS] Fixing the case when user already have the app installed with  access granted for notifications to set suggestion switch "on" by default.

### Testing strategy

- [x] I ensured my code is tested: ✅ test unit ✅ emulator / simulator  
- [ ] I took care to mention breaking changes and extra libs if appropriate

2020-09-15 20:30 UTC, Fausto95 commented
Could you constatify the status(just like NOTIFICATION_TYPE)?
Also, shouldn’t we set the suggestion setting to true on home screen did mount?

2020-09-15 20:32 UTC, alanlanglois commented
> Could you constatify the status(just like NOTIFICATION_TYPE)?
> Also, shouldn’t we set the suggestion setting to true on home screen did mount?

I'm on it :)

2020-09-15 20:54 UTC, alanlanglois commented on src/components/switch.tsx
> +  status: NotificationSettingStatus;
should stay is active IMO, as switch could be used in other case not involving notifications

2020-09-15 21:04 UTC, Fausto95 commented on src/components/switch.tsx
> +  status: NotificationSettingStatus;
Agreed

2020-09-15 21:06 UTC, Fausto95 commented on src/components/switch.tsx
> +  status: NotificationSettingStatus;
So we need to change from `status` to `isActive` here: https://github.com/CoorpAcademy/mobile/blob/31b6944099b2d71d247d0ae8f2f6324c48278ed5/src/screens/settings.tsx#L41

2020-09-15 22:22 UTC, alanlanglois commented on src/components/switch.tsx
> +  status: NotificationSettingStatus;
Are you sure?
I just changed this in the component:
`<Switch isActive={item.status === NOTIFICATION_SETTINGS_STATUS.ACTIVATED}
`
So we can keep a String argument for analytics

2020-09-16 00:54 UTC, Fausto95 requested changes

2020-09-16 00:54 UTC, Fausto95 commented on src/const.ts
> +> = {
IDLE

2020-09-16 00:54 UTC, Fausto95 commented on src/const.ts
> +  DESACTIVATED: 'deactivated',
DEACTIVATED

2020-09-16 08:03 UTC, alanlanglois commented on src/const.ts
> +  DESACTIVATED: 'deactivated',
Excuse ma French...

2020-09-16 15:26 UTC, Fausto95 approved these changes

2020-09-17 08:27 UTC, merged